# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '2-5-8' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 2-5-8
	pod 'Firebase/Core'
	pod 'Firebase/Messaging'
  target '2-5-8Tests' do
    inherit! :search_paths
    # Pods for testing
	pod 'Firebase/Core'
	pod 'Firebase/Messaging'
  end

end
