# Uncomment the next line to define a global platform for your project
platform :ios, '10.2'

target '2-3-2' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 2-3-2
	pod 'FMDB'

  target '2-3-2Tests' do
    inherit! :search_paths
    # Pods for testing
	pod 'FMDB'
  end

  target '2-3-2UITests' do
    inherit! :search_paths
    # Pods for testing
    pod 'FMDB'
  end

end
